# Generated by Django 4.2 on 2025-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegeneration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Генерация комикса', 'verbose_name_plural': 'Генерации комиксов'},
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL комикса'),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='prompt',
            field=models.TextField(verbose_name='Описание для комикса'),
        ),
    ]
